---
- hosts: uf1
  vars:
      splunkver: 6.5.1-f74036626f0c-linux-2.6-x86_64
      slunkforwarderver: 6.5.1-f74036626f0c-linux-2.6-x86_64
      installapps: False
      # ssl_enabled
      # auth_enabled

  tasks:
    - name: Ensure libselinux-python installed
      yum: name=libselinux-python state=present

    - name: Ensure net-tools installed
      yum: name=net-tools state=present

    - name: Ensure wget installed
      yum: name=wget state=present

    - name: Ensure aliases.sh present
      copy: src=files/aliases.sh dest=/etc/profile.d/aliases.sh
            owner=root group=root mode=0644

    - name: Ensure EPEL repo is configured
      shell: rpm -q epel-release || yum install -y http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

    - name: Ensure hostname is in /etc/hosts
      lineinfile:
        dest=/etc/hosts
        regexp="^{{ ansible_default_ipv4.address }}.+$"
        line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"

    - name: Ensure Splunk universal forwarder package installed
      yum:  name=/home/vagrant/sync/sw/splunkforwarder-{{ slunkforwarderver }}.rpm state=present

    - name: Ensure Splunk service is configured
      copy: src=files/splunk.init dest=/etc/init.d/splunk
            owner=root group=root mode=0755
      notify:
        - restart splunk

   ## adding this because keep getting access denied on the "sart nginx service" step so brute force installing nginx first :/
    - name: Install nginx (workaround)
      shell: sudo yum -y install nginx

    - name: Start nginx service
      service: name=nginx state=started enabled=yes
      become: true

    # pulls from EPEL
    - name: Ensure dkms is installed needed to preserve additions thru kernel updates
      yum: name=dkms state=present

    - name: Extract vm additions
      unarchive: src=sw/vmadditions.tar.gz
                 dest=/tmp
                 creates=/tmp/vmadditions

    - name: Install VM additions
      shell: /tmp/additions/VBoxLinuxAdditions.run

    - name: Set splunk admin password
      shell: /opt/splunkforwarder/bin/splunk edit user admin -password splunk -auth admin:changeme  --accept-license

    - name: Enable splunk boot start
      shell: /opt/splunkforwarder/bin/splunk enable boot-start

    - name: Enable deployment server URL for this deployment client
      shell: /opt/splunkforwarder/bin/splunk set deploy-poll 192.168.33.101:8089

    - name: Enable deployment client
      shell: /opt/splunkforwarder/bin/splunk enable deploy-client

    - name: Enable forward server
      shell: /opt/splunkforwarder/bin/splunk add forward-server 192.168.33.102:9997 -auth admin:splunk

    - name: Add second forward server
      shell: /opt/splunkforwarder/bin/splunk add forward-server 192.168.33.103:9997 -auth admin:splunk

    - name: Add monitor
      shell: /opt/splunkforwarder/bin/splunk add monitor /var/log -auth admin:splunk

    - name: restart splunk forwarder
      shell: /opt/splunkforwarder/bin/splunk restart

    - name: restart nginx
      service: name=nginx state=restarted
